//! `HC_ABOUT` command text — mirrors HydroComplete.Civil3D 1.4.0 listing.

pub const ABOUT_LINES: &[&str] = &[
    "=== HydroComplete for Open CAD Studio 0.2.0 ===",
    "  HC_NETWORK       Per-network summary (pipes, length, inverts, diameters, structures)",
    "  HC_PIPES         Manning capacity of every pipe (circular, box, arch)",
    "  HC_PIPES_WRITE   Label Qfull/Vfull on layer HC-CAPACITY",
    "  HC_CAPACITY      Design Q vs Q_full check (d/D, surcharge flag)",
    "  HC_CAPACITY_WRITE Label overloaded pipes on layer HC-CAPACITY",
    "  HC_SIZE          Standard catalog pipe sizing (velocity, % full)",
    "  HC_VALIDATE      Design-criteria review (slope, capacity, velocity, cover, HGL)",
    "  HC_ANALYZE       Full-network analysis (hydrology, routing, HGL, sediment, compliance)",
    "  HC_REVIEW        Design review + state regulatory compliance check",
    "  HC_SCS           SCS CN runoff from catchments",
    "  HC_UNIT_HYDRO    SCS unit hydrograph table output",
    "  HC_SEDIMENT      RUSLE/MUSLE soil loss from catchments",
    "  HC_WQV           Water quality volume calculation",
    "  HC_DETENTION     Detention pond routing (Modified Puls, SCS UH inflow, orifice/weir outlets)",
    "  HC_BMP_SIZE      WQV-based BMP sizing (bioretention, wet pond, sand filter, swale)",
    "  HC_WQ_TRAIN      BMP treatment train with EMC pollutant loads from catchments",
    "  HC_SEDIMENT_BASIN Sediment basin design from peak Q (NCDEQ surface-area method)",
    "  HC_HGL           Steady HGL (normal depth) + junction losses + HC-HGL labels + plan profile",
    "  HC_PREPOST       Pre/post-development peak comparison (SCS UH, multi-storm state depths)",
    "  HC_OPTIMIZE      BMP treatment-train cost optimizer (top 3 chains)",
    "  HC_CULVERT       Culvert headwater (FHWA HDS-5 inlet/outlet control)",
    "  HC_GVF           Gradually varied flow profile (Standard Step, trapezoidal channel)",
    "  HC_PROFILE       Chainage profile plot (invert, crown, optional HGL)",
    "  HC_PROFILE_DXF   Export chainage profile to DXF (invert, crown, optional HGL)",
    "  HC_REPORT        Export formula-transparent HTML Manning + HGL report (free)",
    "  HC_REPORT_PDF    Export formula-transparent PDF Manning + HGL report (Pro)",
    "  HC_RATIONAL      Rational peak Q from catchments + NOAA Atlas 14 IDF presets",
    "  HC_MULTIRP       Per-pipe Q and d/D for 2/10/25/100-yr return periods",
    "  HC_TC            TR-55 segmented time-of-concentration worksheet",
    "  HC_INLETS        HEC-22 inlet check (grate / sag / curb opening)",
    "  HC_NETWORK_EDIT  Edit pipe Q and Manning n overrides (saved per drawing)",
    "  HC_NETWORK_DIAGRAM Export HTML/SVG pipe network schematic from plan topology",
    "  HC_PUMP          Pump station duty-point check (curve vs system head)",
    "  HC_COST          Pipe cost roll-up from diameter catalog ($/LF)",
    "  HC_BACKGROUND    Attach georeferenced raster on HC-BACKGROUND layer",
    "  HC_HYDROGRAPH    Synthetic hydrograph ordinates (SCS, Clark, Snyder)",
    "  HC_ROUTE_HYDRO   Route catchment hydrographs through pipe network",
    "  HC_BIORETENTION  Bioretention routing with underdrain/outlet",
    "  HC_WETLAND       Wetland detention routing",
    "  HC_SOIL          Live SSURGO soil lookup + BMP suitability",
    "  HC_LANDXML       Export pipe network to LandXML 1.2",
    "  HC_LANDXML_IMPORT Import LandXML 1.2 and compare to drawing",
    "  HC_ATLAS14       List Atlas 14 IDF presets + live PFDS fetch info",
    "  HC_ACTIVATE      Activate Pro with email + beta token (hc_live_*)",
    "  HC_LICENSE       Show Free/Pro license status and activation info",
    "  HC_INLET / HC_JUNCTION / HC_OUTFALL / HC_PIPE  Place network geometry (OpenCAD)",
    "  HC_EDIT          Edit structure or pipe XDATA",
    "  HC_ABOUT         This list",
    "  Engine: Rational, TR-55 Tc, Manning (circular/box/arch), GVF, detention, BMP/WQV, LandXML, HEC-22.",
];