#!/usr/bin/env python3
"""Generate crates/hydrocomplete/src/state_compliance_data.rs from C# StateComplianceData.cs."""
import re
import pathlib

CS = pathlib.Path(__file__).resolve().parents[2] / "hydrocomplete-civil3d" / "src" / "HydroComplete.Engine" / "StateComplianceData.cs"
OUT = pathlib.Path(__file__).resolve().parents[1] / "crates" / "hydrocomplete" / "src" / "state_compliance_data.rs"

text = CS.read_text(encoding="utf-8")
pattern = re.compile(
    r'\["([A-Z0-9]+)"\] = new StateComplianceConfig\s*\{([^}]+)\}',
    re.DOTALL,
)
blocks = pattern.findall(text)

def field(body: str, name: str, default=None):
    m = re.search(rf"{name} = ([^,\n]+)", body)
    if not m:
        return default
    val = m.group(1).strip()
    if val == "true":
        return "true"
    if val == "false":
        return "false"
    if val.endswith('"'):
        return val
    if val.endswith("null"):
        return "None"
    if "." in val or "e" in val.lower():
        return val
    return f"{val}.0"

lines = [
    "// SPDX-License-Identifier: GPL-3.0-only",
    "// Auto-generated by scripts/gen_state_compliance.py — do not edit by hand.",
    "",
    "use super::StateComplianceConfig;",
    "",
    "pub fn all_configs() -> &'static [(&'static str, StateComplianceConfig)] {",
    "    &CONFIGS",
    "}",
    "",
    "pub const EMBEDDED_STATE_COUNT: usize = 53;",
    "",
    "static CONFIGS: &[(&str, StateComplianceConfig)] = &[",
]

non_default = 0
for code, body in blocks:
    rw = field(body, "RoadwayTssRemovalPercent", "None")
    if rw != "None" and not rw.endswith(".0"):
        rw = f"Some({rw})"
    elif rw != "None":
        rw = f"Some({rw})"
    cfg = (
        f'    ("{code}", StateComplianceConfig {{\n'
        f'        code: "{code}",\n'
        f'        name: {field(body, "Name")},\n'
        f'        regulatory_body: {field(body, "RegulatoryBody")},\n'
        f'        design_storm_inches: {field(body, "DesignStormInches")},\n'
        f'        wq_volume_factor_inches: {field(body, "WqVolumeFactorInches")},\n'
        f'        peak_attenuation_percent: {field(body, "PeakAttenuationPercent")},\n'
        f'        drawdown_min_hours: {field(body, "DrawdownMinHours")},\n'
        f'        drawdown_max_hours: {field(body, "DrawdownMaxHours")},\n'
        f'        tss_removal_percent: {field(body, "TssRemovalPercent")},\n'
        f'        tn_removal_percent: {field(body, "TnRemovalPercent")},\n'
        f'        tp_removal_percent: {field(body, "TpRemovalPercent")},\n'
        f'        roadway_tss_removal_percent: {rw},\n'
        f'        tolerable_soil_loss_tons_per_ac_yr: {field(body, "TolerableSoilLossTonsPerAcYr")},\n'
        f'        default_r_factor: {field(body, "DefaultRFactor")},\n'
        f'        volume_control_required: {field(body, "VolumeControlRequired")},\n'
        f"    }}),"
    )
    lines.append(cfg)
    if code != "DEFAULT":
        non_default += 1

lines.append("];")
OUT.write_text("\n".join(lines) + "\n", encoding="utf-8")
print(f"Wrote {len(blocks)} configs ({non_default} jurisdictions) to {OUT}")